api_platform:
    title: 'API for Books Campus Academy'
    description: 'A Symfony API to manage a database of books for cmapus academy.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]